heat_template_version: 2015-04-30

description: Template to deploy 3 instances

parameters:
  key_name:
    type: string
  network_name:
    type: string
  network_name_floating:
    type: string

resources:

  web_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 80
          port_range_max: 80
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 443
          port_range_max: 443
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 3306       # mysql port
          port_range_max: 3306

  instance1:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: ubuntu-22.04
      flavor: m1.small
      networks:
      - port: { get_resource: server1_port }

  instance2:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: ubuntu-22.04
      flavor: m1.small
      networks:
        - port: { get_resource: server2_port}
  
  instance3:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: ubuntu-22.04
      flavor: m1.small
      networks:
      - port: { get_resource: server3_port }
  
  server1_port:
    type: OS::Neutron::Port
    properties:
      network_id:  { get_param: network_name } # sutdents.net ID
      security_groups:
        - default
        - { get_resource: web_secgroup }
  
  server2_port:
    type: OS::Neutron::Port
    properties:
      network_id:  { get_param: network_name } # sutdents.net ID
      security_groups:
          - default
          - { get_resource: web_secgroup }
  
  server3_port:
    type: OS::Neutron::Port
    properties:
      network_id:  { get_param: network_name } # sutdents.net ID
      security_groups:
          - default
          - { get_resource: web_secgroup }
  
  
  server1_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: network_name_floating } # mngm.net ID

  association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: server1_floating_ip }
      port_id: { get_resource: server1_port }


  
  
